name: Build project

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set uo java
      uses: actions/setup-java@v3

    - name: Build maven
      run: mvn -B clean package

#        Дальше деплой на ssh сервер

#      - run: mkdir "$HOME/.ssh/key"
#      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
#      - run: chmod 600 "$HOME/.ssh/key"
#
#      - run: cd target && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no -p port" --archive --compress --delete Builder.jar user@8.8.8.8:/folder

    - uses: actions/upload-artifact@v3
      with:
        name: Builder1 # тут любое имя
        path: target/Builder.jar # Тут расположение файла